const SET_FROM_CURRENCY = 'SET_FROM_CURRENCY';
const SET_TO_CURRENCY = 'SET_TO_CURRENCY';
const SET_VALUE = 'SET_VALUE';
const REQUEST_API = 'REQUEST_API';
const RECEIVE_RESPONSE = 'RECIEVE_API';
const ACCESS_DENIED = 'ACCESS_DENIED';
const API_ERROR = `API_ERROR`;
const LOADING = `LOADING`;
const SET_HISTORY = `SET_HISTORY`;

export { 
         SET_FROM_CURRENCY, SET_TO_CURRENCY, 
         SET_VALUE, REQUEST_API, RECEIVE_RESPONSE,
         ACCESS_DENIED, API_ERROR, LOADING,SET_HISTORY
       };